os: linux
dist: xenial
language: cpp
compiler: clang

before_install:
  - sudo apt-get -qq update

branches:
  except:
  - lilypond

branches:
  only:
  - dev
  - master

script: 
   - make -C build -j 2
   - which cmake
   - cmake --version
   - sudo make -C build install 
   - make -C validation travis -j 2
