os: linux
dist: Trusty
language: cpp
compiler: gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gcc-4.9 -y

branches:
  only:
  - dev
  - lilypond
  - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

script: 
    - echo $(CXX)
    - echo $(g++ --version)
    - cd cmake 
    - cmake .
    - make

