os: linux
dist: Trusty
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    
before_install:
  - sudo apt-get -qq update

branches:
  only:
  - dev
  - lilypond
  - master

script: 
    - g++ --version
    - gcc --version
    - gcc-4.9 --version
    - cd cmake 
    - cmake .
    - make

