dist: trusty
sudo: required
language: cpp
compiler: gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"
    
branches:
  only:
  - dev
  - lilypond
  - master

script: 
    - cd cmake && cmake . && make -j 2
    - cd ../validation && make read XMLREAD=../cmake/xmlread -j 2

