os: linux
dist: Trusty
language: cpp
compiler: gcc
    
before_install:
  - sudo apt-get -qq update

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

branches:
  only:
  - dev
  - lilypond
  - master

script: 
    - cd cmake 
    - cmake .
    - make -j 2

