os: linux
dist: trusty
language: cpp
compiler: g++

before_install:
  - sudo apt-get -qq update

branches:
  only:
  - dev
  - lilypond
  - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

script: 
    - echo $(g++ --version)
    - cd cmake 
    - cmake .
    - make
