os: linux
dist: Trusty
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install gcc-4.9 -y

branches:
  only:
  - dev
  - lilypond
  - master

script: 
    - g++ --version
    - cd cmake 
    - cmake .
    - make

