dist: trusty
sudo: required
language: cpp
compiler: gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
    - eval "${MATRIX_EVAL}"
    
#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get -qq update
#  - sudo apt-get install -qq g++-5

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - gcc-5
#    - g++-5

branches:
  only:
  - dev
  - lilypond
  - master

script: 
    - gcc-5 --version
    - g++-5 --version
    - cd cmake 
    - cmake . 
    - make -j 2

