version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: >-
    cd build

    mkdir win32 win64

    cd win32

    cmake .. -G "Visual Studio 14 2015"

    cmake --build . --config Release

    cd ../win64

    cmake .. -G "Visual Studio 14 2015 Win64"

    cmake --build . --config Release